---
- name: Install Support packages
  apt: name={{item}} state=present
  with_items:
  - curl
  - openssh-server
  - ca-certificates
  - postfix

- name: Run gitlab curl
  shell: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash

- name: Run gitlab curl
  shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | sudo bash

- name: Install gitlab
  apt: name={{item}} state=present
  with_items:
  - gitlab-ce
  - gitlab-ci-multi-runner
