---
- name: Launch ec2
  ec2:
    key_name: "{{ec2_key_name}}"
    instance_type: "{{instance_type}}"
    image: "{{ami}}"
    group: "{{sg_group}}"
    wait: yes
    wait_timeout: 500
    termination_protection : yes
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 30
        delete_on_termination: true
    count: 1
    vpc_subnet_id: "{{vpc_subnet}}"
    assign_public_ip: yes
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{aws_region}}"
  register: ec2info

- name: Assign eip
  ec2_eip:
    device_id: "{{ec2info.instances[0].id}}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{aws_region}}"
  register: ec2info

- name: Print ec2info
  debug: var=ec2info
