---
- name: Create ec2 security group
  ec2_group:
        state: present
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        name: "SG-AssaultCube"
        description: "AssaultCube-Server security group - open ports 28763"
        vpc_id: "{{vpc_id}}"
        region: "{{aws_region}}"
        rules:
          - proto: udp
            from_port: 28762
            to_port: 28764
            cidr_ip: 0.0.0.0/0
  register: sg

- debug: var=sg
