---
- name: Adding Cassandra repo
  apt_repository: repo='deb http://www.apache.org/dist/cassandra/debian 22x main' state=present

- name: Add the Cassandra APT key
  apt_key: keyserver=pgp.mit.edu id=F758CE318D77295D state=present

- name: Add the Cassandra APT key
  apt_key: keyserver=pgp.mit.edu id=2B5C1B00 state=present

- name: Add the Cassandra APT key
  apt_key: keyserver=pgp.mit.edu id=0353B12C state=present

- name: Install Cassandra
  apt: name={{item}} state=present update_cache=yes
  with_items:
   - cassandra

- name: Stop Cassandra
  service: name=cassandra state=stopped

- name: Create Cassandra directory
  file: path={{cassandra_data}}/cassandra state=directory owner=cassandra group=cassandra

- name: Configure Cassandra
  template: src={{item.src}} dest={{item.dest}}
  with_items:
  - { src: cassandra.j2, dest: /etc/cassandra/cassandra.yaml }
  - { src: cassandra_service.j2, dest: /etc/init.dcassandra }

- name: Start Cassandra
  service: name=cassandra state=started
