---
- name: Create ec2 security group
  ec2_group:
        state: present
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        name: "SG-OpenRA"
        description: "OpenRA security group - open ports 1234"
        vpc_id: "{{vpc_id}}"
        region: "{{aws_region}}"
        rules:
          - proto: tcp
            from_port: 1234
            to_port: 1234
            cidr_ip: 0.0.0.0/0
  register: sg

- debug: var=sg
