---
- name: Gather ec2 facts
  ec2_facts:
  when: dc_env == "aws"

- name: Remove instance from ELB
  local_action:
    module: ec2_elb
    instance_id: "{{ansible_ec2_instance_id}}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{ansible_ec2_placement_region}}"
    state: absent
  when: dc_env == "aws"

- name: Download phpmyadmin
  get_url: url={{phpmyadmin_url}} dest=/opt validate_certs=False
  tags:
    - deployment

- name: Extract phpmyadmin
  unarchive: src=/opt/{{phpmyadmin_version}}.zip dest=/opt copy=no
  tags:
    - deployment

- name: Configure phpmyadmin
  template: src=config.inc.php.j2 dest=/opt/{{phpmyadmin_version}}/config.inc.php

- name: Stop Nginx
  service: name=nginx state=stopped

- name: Update Nginx configuration
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    #- { src: virtualhost_phpmyadmin.j2, dest: /etc/nginx/sites-available/virtualhost_phpmyadmin }
    #- { src: virtualhost_phpmyadmin.j2, dest: /etc/nginx/sites-enabled/virtualhost_phpmyadmin }
    - { src: virtualhost_phpmyadmin_ssl.j2, dest: /etc/nginx/sites-available/virtualhost_phpmyadmin-ssl }
    - { src: virtualhost_phpmyadmin_ssl.j2, dest: /etc/nginx/sites-enabled/virtualhost_phpmyadmin-ssl }
  tags:
    - nginx-virtualhost-configuration

- name: Start Nginx
  service: name=nginx state=started

- name: Attach instance from ELB
  local_action:
    module: ec2_elb
    instance_id: "{{ansible_ec2_instance_id}}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{ansible_ec2_placement_region}}"
    ec2_elbs: "{{item}}"
    wait: yes
    wait_timeout: 60
    state: present
  when: dc_env == "aws"
  with_items: ec2_elbs
